### ISSUE TITLE
New Intel:  [firebaseZ]

### ISSUE THREAD

**Issue by CannonAka** [Miss-placed/DECLASSIFIED#407]
### Name

Blacksmiths and Architects

### Faction

Requiem

### Season

Season 1

### Type of intel

Radio Transmission

### Description

Next to the ammo crate sitting on the edge of the table

### Map

firebaseZ

### Location Coordinates

[208.42566965486716, 373.4603320044914]

**Comment by sol3uk** [comment]
![image](https://user-images.githubusercontent.com/26093813/212640363-e8e9de84-07c2-45e7-b65d-302513815f55.png)
We already have this in the app the reason it doesn't show a location however, is because we haven't mapped all the possible radio intel items to the appropriate radios on the map. Apologies about any confusion.
